Repository Anesthez/CSC-207-Group-Project-Group86, pull requests merged in 2022-12, with the labels that each got.

#99 Implementation_TopicScreen, HottestTopicScreen_Chen Jiang
  README.md
  database/topic.csv
  src/databaseInterface/test.java
  src/entity/Topic.java
  src/model/request/TopicRequestModel.java
  src/model/response/TopicResponseModel.java
  src/ui/screens/topicScreens/HottestTopicScreen.java
  src/ui/screens/topicScreens/TopicScreen.java
  src/useCases/TopicUseCases.java
Labels: enhancement, Implementation

#98 Test_ChatUseCasesTests_LemengDai
  CSC-207-Group-Project.iml
  src/commands/ChatCommand.java
  src/entity/inputboundary/Context.java
  src/presenter/CommentPresenter.java
  src/useCases/ChatUseCases.java
  test/UseCases/ChatUseCasesTests.java
Labels: tests

#103 Modificatioin_HottestTopicScreen, TopicScreen, ShowTopicScreen_Chen Jiang
  src/ui/premiumScreens/topicScreens/HottestTopicScreen.java
  src/ui/premiumScreens/topicScreens/ShowTopicsScreen.java
  src/ui/premiumScreens/topicScreens/TopicScreen.java
  src/ui/screens/topicScreens/HottestTopicScreen.java
Labels: documentation, enhancement, Implementation

#67 UI_Design_Stage_3_PR_2
  assets/images/addpost.png
  assets/images/addpost1080.png
  assets/images/back.png
  assets/images/back1080.png
  assets/images/backgroundtrans.png
  assets/images/comment.png
  assets/images/comment1080.png
  assets/images/iconbg.png
  assets/images/liked.png
  assets/images/liked1080.png
  assets/images/postsmall.png
  assets/images/unlike.png
  assets/images/unlike1080.png
  database/post.csv
  database/post_liked.csv
  src/ui/premiumScreens/PremiumMainScreen.java
  src/ui/premiumScreens/friendsScreens/FriendsScreen.java
  src/ui/premiumScreens/friendsScreens/chatScreens/ChatScreen.java
  src/ui/premiumScreens/postScreens/HotPostScreen.java
  src/ui/premiumScreens/postScreens/PostScreen.java
  src/ui/premiumScreens/postScreens/ShowPostScreen.java
  src/ui/premiumScreens/postScreens/UploadPostScreen.java
  src/ui/premiumScreens/postScreens/commentScreens/ShowCommentScreen.java
  src/ui/screens/LoginScreen.java
  src/ui/screens/RegisterScreen.java
Labels: documentation, enhancement, UI

#108 Implementation_TopicUseCases_Kevin_TQJ
  src/useCases/AddPostsToTopicUsesCase.java
  src/useCases/GetMaxTopicUseCase.java
  src/useCases/GetTopPostsUseCase.java
  src/useCases/GetTopTopicsUseCase.java
  src/useCases/UseCaseFacade/TopicUseCasesFacade.java
Labels: Implementation
